[package]
authors = ["d0iasm"]
name = "vulbr"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.4.8"
gdk4 = "0.4.8"
gio = "0.15.11"
once_cell = "1.11.0"
dns-lookup = "1.0.8"
gdk4-sys = "0.4.8"
gsk4-sys = "0.4.8"
